import { Transcript } from "./types";

export const SAMPLE: Transcript = {
  registerNo: "23BCE0000",
  name: "JOHN MATTHEW CARTER",
  program: "B.Tech. - Computer Science and Engineering",
  school: "SCOPE - School of Computer Science and Engineering",
  statedCgpa: 9.51,
  creditsRequiredTotal: 162,
  courses: [
    { slNo: 1, code: "BCSE101E", title: "Computer Programming: Python", type: "ETL", credits: 3.0, grade: "A", examMonth: "Dec-2023", distribution: "FC" },
    { slNo: 2, code: "BCSE101N", title: "Introduction to Engineering", type: "PJT", credits: 1.0, grade: "P", examMonth: "Dec-2023", distribution: "NGCR" },
    { slNo: 3, code: "BMAT101L", title: "Calculus", type: "TH", credits: 3.0, grade: "S", examMonth: "Dec-2023", distribution: "FC" },
    { slNo: 4, code: "BMAT101P", title: "Calculus Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Dec-2023", distribution: "FC" },
    { slNo: 5, code: "BMEE102P", title: "Engineering Design Visualisation Lab", type: "LO", credits: 2.0, grade: "A", examMonth: "Dec-2023", distribution: "OE" },
    { slNo: 6, code: "BMEE201L", title: "Engineering Mechanics", type: "TH", credits: 3.0, grade: "S", examMonth: "Dec-2023", distribution: "OE" },
    { slNo: 7, code: "BPHY101L", title: "Engineering Physics", type: "TH", credits: 3.0, grade: "S", examMonth: "Dec-2023", distribution: "FC" },
    { slNo: 8, code: "BPHY101P", title: "Engineering Physics Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Dec-2023", distribution: "FC" },
    { slNo: 9, code: "BSTS201P", title: "Qualitative Skills Practice I", type: "SS", credits: 1.5, grade: "S", examMonth: "Dec-2023", distribution: "FC" },
    { slNo: 10, code: "BCHY101L", title: "Engineering Chemistry", type: "TH", credits: 3.0, grade: "A", examMonth: "May-2024", distribution: "FC" },
    { slNo: 11, code: "BCHY101P", title: "Engineering Chemistry Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "May-2024", distribution: "FC" },
    { slNo: 12, code: "BCSE103E", title: "Computer Programming: Java", type: "ETL", credits: 3.0, grade: "S", examMonth: "May-2024", distribution: "FC" },
    { slNo: 13, code: "BEEE102L", title: "Basic Electrical and Electronics Engineering", type: "TH", credits: 3.0, grade: "A", examMonth: "May-2024", distribution: "FC" },
    { slNo: 14, code: "BEEE102P", title: "Basic Electrical and Electronics Engineering Lab", type: "LO", credits: 1.0, grade: "S", examMonth: "May-2024", distribution: "FC" },
    { slNo: 15, code: "BENG101L", title: "Technical English Communication", type: "TH", credits: 2.0, grade: "S", examMonth: "May-2024", distribution: "FC" },
    { slNo: 16, code: "BENG101P", title: "Technical English Communication Lab", type: "LO", credits: 1.0, grade: "S", examMonth: "May-2024", distribution: "FC" },
    { slNo: 17, code: "BHUM101N", title: "Ethics and Values", type: "OC", credits: 2.0, grade: "P", examMonth: "May-2024", distribution: "NGCR" },
    { slNo: 18, code: "BMAT102L", title: "Differential Equations and Transforms", type: "TH", credits: 4.0, grade: "A", examMonth: "May-2024", distribution: "FC" },
    { slNo: 19, code: "BMEE203L", title: "Engineering Thermodynamics", type: "TH", credits: 3.0, grade: "A", examMonth: "May-2024", distribution: "OE" },
    { slNo: 20, code: "BSTS101P", title: "Quantitative Skills Practice I", type: "SS", credits: 1.5, grade: "S", examMonth: "May-2024", distribution: "FC" },
    { slNo: 21, code: "BCHY102N", title: "Environmental Sciences", type: "OC", credits: 2.0, grade: "P", examMonth: "Nov-2024", distribution: "NGCR" },
    { slNo: 22, code: "BECE102L", title: "Digital Systems Design", type: "TH", credits: 3.0, grade: "S", examMonth: "Nov-2024", distribution: "DLES" },
    { slNo: 23, code: "BECE102P", title: "Digital Systems Design Lab", type: "LO", credits: 1.0, grade: "S", examMonth: "Nov-2024", distribution: "DLES" },
    { slNo: 24, code: "BENG102P", title: "Technical Report Writing", type: "LO", credits: 1.0, grade: "A", examMonth: "Nov-2024", distribution: "FC" },
    { slNo: 25, code: "BMAT201L", title: "Complex Variables and Linear Algebra", type: "TH", credits: 4.0, grade: "A", examMonth: "Nov-2024", distribution: "FC" },
    { slNo: 26, code: "BMAT205L", title: "Discrete Mathematics and Graph Theory", type: "TH", credits: 4.0, grade: "S", examMonth: "Nov-2024", distribution: "DLES" },
    { slNo: 27, code: "BMGT108L", title: "Entrepreneurship", type: "TH", credits: 3.0, grade: "A", examMonth: "Nov-2024", distribution: "OE" },
    { slNo: 28, code: "BSTS202P", title: "Qualitative Skills Practice II", type: "SS", credits: 1.5, grade: "S", examMonth: "Nov-2024", distribution: "FC" },
    { slNo: 29, code: "ACXC185N", title: "Mobility Engineering in Land, Air and Sea", type: "ECA", credits: 2.0, grade: "P", examMonth: "Apr-2025", distribution: "NGCR" },
    { slNo: 30, code: "BARB101L", title: "Arabic", type: "TH", credits: 2.0, grade: "S", examMonth: "Apr-2025", distribution: "FC" },
    { slNo: 31, code: "BCSE102L", title: "Structured and Object-Oriented Programming", type: "TH", credits: 2.0, grade: "A", examMonth: "Apr-2025", distribution: "FC" },
    { slNo: 32, code: "BCSE102P", title: "Structured and Object-Oriented Programming Lab", type: "LO", credits: 2.0, grade: "A", examMonth: "Apr-2025", distribution: "FC" },
    { slNo: 33, code: "BCSE205L", title: "Computer Architecture and Organization", type: "TH", credits: 3.0, grade: "A", examMonth: "Apr-2025", distribution: "DC" },
    { slNo: 34, code: "BCSE304L", title: "Theory of Computation", type: "TH", credits: 3.0, grade: "S", examMonth: "Apr-2025", distribution: "DC" },
    { slNo: 35, code: "BMAT202L", title: "Probability and Statistics", type: "TH", credits: 3.0, grade: "A", examMonth: "Apr-2025", distribution: "FC" },
    { slNo: 36, code: "BMAT202P", title: "Probability and Statistics Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Apr-2025", distribution: "FC" },
    { slNo: 37, code: "BSSC101N", title: "Essence of Traditional Knowledge", type: "OC", credits: 2.0, grade: "P", examMonth: "Apr-2025", distribution: "NGCR" },
    { slNo: 38, code: "BSTS102P", title: "Quantitative Skills Practice II", type: "SS", credits: 1.5, grade: "A", examMonth: "Apr-2025", distribution: "FC" },
    { slNo: 39, code: "BCSE302L", title: "Database Systems", type: "TH", credits: 3.0, grade: "S", examMonth: "Nov-2025", distribution: "DC" },
    { slNo: 40, code: "BCSE302P", title: "Database Systems Lab", type: "LO", credits: 1.0, grade: "S", examMonth: "Nov-2025", distribution: "DC" },
    { slNo: 41, code: "BCSE303L", title: "Operating Systems", type: "TH", credits: 3.0, grade: "S", examMonth: "Nov-2025", distribution: "DC" },
    { slNo: 42, code: "BCSE303P", title: "Operating Systems Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Nov-2025", distribution: "DC" },
    { slNo: 43, code: "BCSE306L", title: "Artificial Intelligence", type: "TH", credits: 3.0, grade: "S", examMonth: "Nov-2025", distribution: "DC" },
    { slNo: 44, code: "BCSE307L", title: "Compiler Design", type: "TH", credits: 3.0, grade: "S", examMonth: "Nov-2025", distribution: "DC" },
    { slNo: 45, code: "BCSE307P", title: "Compiler Design Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Nov-2025", distribution: "DC" },
    { slNo: 46, code: "BCSE355L", title: "Cloud Architecture Design", type: "TH", credits: 3.0, grade: "S", examMonth: "Nov-2025", distribution: "OE" },
    { slNo: 47, code: "BECE204L", title: "Microprocessors and Microcontrollers", type: "TH", credits: 3.0, grade: "A", examMonth: "Nov-2025", distribution: "DLES" },
    { slNo: 48, code: "BECE204P", title: "Microprocessors and Microcontrollers Lab", type: "LO", credits: 1.0, grade: "S", examMonth: "Nov-2025", distribution: "DLES" },
    { slNo: 49, code: "BSSC102N", title: "Indian Constitution", type: "OC", credits: 2.0, grade: "P", examMonth: "Nov-2025", distribution: "NGCR" },
    { slNo: 50, code: "BSTS301P", title: "Advanced Competitive Coding - I", type: "SS", credits: 1.5, grade: "A", examMonth: "Nov-2025", distribution: "OE" },
    { slNo: 51, code: "BCSE203E", title: "Web Programming", type: "ETL", credits: 3.0, grade: "S", examMonth: "Apr-2026", distribution: "DC" },
    { slNo: 52, code: "BCSE301L", title: "Software Engineering", type: "TH", credits: 3.0, grade: "A", examMonth: "Apr-2026", distribution: "DC" },
    { slNo: 53, code: "BCSE301P", title: "Software Engineering Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Apr-2026", distribution: "DC" },
    { slNo: 54, code: "BCSE305L", title: "Embedded Systems", type: "TH", credits: 3.0, grade: "S", examMonth: "Apr-2026", distribution: "DC" },
    { slNo: 55, code: "BCSE309L", title: "Cryptography and Network Security", type: "TH", credits: 3.0, grade: "S", examMonth: "Apr-2026", distribution: "DC" },
    { slNo: 56, code: "BCSE309P", title: "Cryptography and Network Security Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Apr-2026", distribution: "DC" },
    { slNo: 57, code: "BCSE317L", title: "Information Security", type: "TH", credits: 3.0, grade: "A", examMonth: "Apr-2026", distribution: "SPE" },
    { slNo: 58, code: "BCSE318L", title: "Data Privacy", type: "TH", credits: 3.0, grade: "A", examMonth: "Apr-2026", distribution: "SPE" },
    { slNo: 59, code: "BCSE319L", title: "Penetration Testing and Vulnerability Analysis", type: "TH", credits: 2.0, grade: "S", examMonth: "Apr-2026", distribution: "SPE" },
    { slNo: 60, code: "BCSE319P", title: "Penetration Testing and Vulnerability Analysis Lab", type: "LO", credits: 1.0, grade: "A", examMonth: "Apr-2026", distribution: "SPE" },
    { slNo: 61, code: "BSTS302P", title: "Advanced Competitive Coding - II", type: "SS", credits: 1.5, grade: "S", examMonth: "Apr-2026", distribution: "OE" },
  ],
  curriculum: [
    { category: "Foundation Core", required: 53.0, earned: 50.0 },
    { category: "Discipline-linked Engineering Sciences", required: 12.0, earned: 12.0 },
    { category: "Discipline Core", required: 47.0, earned: 35.0 },
    { category: "Specialization Elective", required: 21.0, earned: 9.0 },
    { category: "Projects and Internship", required: 9.0, earned: 0.0 },
    { category: "Open Elective", required: 9.0, earned: 17.0 },
    { category: "Bridge Course", required: 0.0, earned: 0.0 },
    { category: "Non-graded Core Requirement", required: 11.0, earned: 11.0 },
  ],
};

